import { ProjectBlueprint } from "./types";

export function generateMarkdownBlueprint(blueprint: ProjectBlueprint): string {
  const featuresMd = blueprint.coreFeatures
    .map(
      (f, i) =>
        `${i + 1}. **${f.title}** [Priority: ${f.priority}]\n   ${f.description}`
    )
    .join("\n\n");

  const techStackMd = `
- **Frontend:** ${blueprint.techStack.frontend.join(", ") || "None"}
- **Backend:** ${blueprint.techStack.backend.join(", ") || "None"}
- **Database:** ${blueprint.techStack.database.join(", ") || "None"}
- **Cloud & DevOps:** ${blueprint.techStack.cloudDevOps.join(", ") || "None"}
- **AI / ML / Data:** ${blueprint.techStack.aiMl.join(", ") || "None"}
`.trim();

  const roadmapMd = blueprint.roadmap
    .map((r) => {
      const milestones = r.milestones.map((m) => `  - [ ] ${m}`).join("\n");
      const deliverables = r.deliverables.map((d) => `  - **Deliverable:** ${d}`).join("\n");
      return `### Phase ${r.phaseNumber}: ${r.title} (${r.durationWeeks} Weeks)\n${milestones}\n${deliverables}`;
    })
    .join("\n\n");

  const risksMd = blueprint.risksAndChallenges
    .map(
      (rc, i) =>
        `${i + 1}. **Risk:** ${rc.risk} *(Severity: ${rc.severity})*\n   - **Mitigation:** ${rc.mitigation}`
    )
    .join("\n\n");

  return `# Final-Year Capstone Project Blueprint: ${blueprint.title}

> **Concept:** ${blueprint.concept}
> **Target Difficulty:** ${blueprint.difficulty} | **Scope:** ${blueprint.estimatedScope.totalWeeks} Weeks (~${blueprint.estimatedScope.hoursPerWeek} hrs/week) | **Team:** ${blueprint.estimatedScope.teamSizeRecommendation}

---

## 1. Problem Statement
${blueprint.problem}

## 2. Target Users & Stakeholders
${blueprint.targetUsers.map((u) => `- ${u}`).join("\n")}

## 3. Student Suitability Analysis
${blueprint.suitability}

## 4. System Architecture Overview
${blueprint.architectureOverview}

## 5. Technology Stack
${techStackMd}

## 6. AI / ML Component Specification
- **Included:** ${blueprint.aiMlComponent.included ? "Yes" : "No"}
- **Purpose & Role:** ${blueprint.aiMlComponent.description}
- **Recommended Model / API:** ${blueprint.aiMlComponent.modelOrApi}
- **Data Requirements:** ${blueprint.aiMlComponent.dataRequirements}
- **Suggested Datasets:** ${blueprint.aiMlComponent.datasetRecommendation}

## 7. Core Functional Features
${featuresMd}

## 8. 3-Week Proof of Concept (MVP Version)
- **Summary:** ${blueprint.mvpVersion.summary}
- **Build Timeline:** ${blueprint.mvpVersion.buildTimelineWeeks} Weeks
- **Core Deliverable:** ${blueprint.mvpVersion.deliverable}
- **Key MVP Features:**
${blueprint.mvpVersion.keyFeatures.map((f) => `  - ${f}`).join("\n")}

## 9. Phased Development Roadmap
${roadmapMd}

## 10. Risks, Challenges & Mitigations
${risksMd}

## 11. Possible Improvements (v1.1+)
${blueprint.possibleImprovements.map((imp) => `- ${imp}`).join("\n")}

## 12. Future Academic Scope & Research Angles
${blueprint.futureScope.map((scope) => `- ${scope}`).join("\n")}

---
*Generated by CapstoneAI — Production Final-Year Project Architect for Students.*
`;
}
