import { ProjectBlueprint } from "./types";

export function generateMarkdownBlueprint(blueprint: ProjectBlueprint): string {
  const featuresMd = blueprint.coreFeatures
    .map(
      (f, i) =>
        `${i + 1}. **${f.title}** [Priority: ${f.priority}]\n   ${f.description}`
    )
    .join("\n\n");

  const techStackMd = `
- **Frontend:** ${blueprint.techStack.frontend.join(", ") || "None"}
- **Backend:** ${blueprint.techStack.backend.join(", ") || "None"}
- **Database:** ${blueprint.techStack.database.join(", ") || "None"}
- **Cloud & DevOps:** ${blueprint.techStack.cloudDevOps.join(", ") || "None"}
- **AI / ML / Data:** ${blueprint.techStack.aiMl.join(", ") || "None"}
`.trim();

  const roadmapMd = blueprint.roadmap
    .map((r) => {
      const milestones = r.milestones.map((m) => `  - [ ] ${m}`).join("\n");
      const deliverables = r.deliverables.map((d) => `  - **Deliverable:** ${d}`).join("\n");
      return `### Phase ${r.phaseNumber}: ${r.title} (${r.durationWeeks} Weeks)\n${milestones}\n${deliverables}`;
    })
    .join("\n\n");

  const risksMd = blueprint.risksAndChallenges
    .map(
      (rc, i) =>
        `${i + 1}. **Risk:** ${rc.risk} *(Severity: ${rc.severity})*\n   - **Mitigation:** ${rc.mitigation}`
    )
    .join("\n\n");

  const evalSection = blueprint.evaluation
    ? `
## 1. Project Reality Check & Feasibility Evaluation
| Evaluation Metric | Score | Assessment |
| :--- | :--- | :--- |
| **Overall Feasibility** | **${blueprint.evaluation.feasibilityScore}/100** | ${blueprint.evaluation.feasibilityScore >= 90 ? "Excellent Viability" : "Solid Viability"} |
| **Skill Fit** | **${blueprint.evaluation.skillFitScore}/100** | Direct match with student competencies |
| **Time Feasibility** | **${blueprint.evaluation.timeFeasibilityScore}/100** | Optimized for ${blueprint.estimatedScope.totalWeeks}-week scope |
| **Resource Feasibility** | **${blueprint.evaluation.resourceFeasibilityScore}/100** | Tailored for ${blueprint.estimatedScope.teamSizeRecommendation} |
| **Innovation & Differentiation** | **${blueprint.evaluation.innovationScore}/100** | Novel architectural and workflow angle |
| **Real-World Impact** | **${blueprint.evaluation.impactScore}/100** | Measurable domain outcome |

### Why This Works
${blueprint.evaluation.whyThisWorks}

### Key Risks & Targeted Mitigations
${blueprint.evaluation.keyRisks.map((r, i) => `- **Risk:** ${r}\n  - **Mitigation:** ${blueprint.evaluation.riskMitigations[i] || "Apply standard modularization and graceful degradation."}`).join("\n")}

### How to Differentiate This Project
${blueprint.evaluation.differentiationSuggestions.map((d) => `- ${d}`).join("\n")}
`.trim()
    : "";

  return `# Final-Year Capstone Project Blueprint: ${blueprint.title}

> **Concept:** ${blueprint.concept}
> **Target Difficulty:** ${blueprint.difficulty} | **Scope:** ${blueprint.estimatedScope.totalWeeks} Weeks (~${blueprint.estimatedScope.hoursPerWeek} hrs/week) | **Team:** ${blueprint.estimatedScope.teamSizeRecommendation}

---

${evalSection}

## 2. Problem Statement
${blueprint.problem}

## 3. Target Users & Stakeholders
${blueprint.targetUsers.map((u) => `- ${u}`).join("\n")}

## 4. Student Suitability Analysis
${blueprint.suitability}

## 5. System Architecture Overview
${blueprint.architectureOverview}

## 6. Technology Stack
${techStackMd}

## 7. AI / ML Component Specification
- **Included:** ${blueprint.aiMlComponent.included ? "Yes" : "No"}
- **Purpose & Role:** ${blueprint.aiMlComponent.description}
- **Recommended Model / API:** ${blueprint.aiMlComponent.modelOrApi}
- **Data Requirements:** ${blueprint.aiMlComponent.dataRequirements}
- **Suggested Datasets:** ${blueprint.aiMlComponent.datasetRecommendation}

## 8. Core Functional Features
${featuresMd}

## 9. 3-Week Proof of Concept (MVP Version)
- **Summary:** ${blueprint.mvpVersion.summary}
- **Build Timeline:** ${blueprint.mvpVersion.buildTimelineWeeks} Weeks
- **Core Deliverable:** ${blueprint.mvpVersion.deliverable}
- **Key MVP Features:**
${blueprint.mvpVersion.keyFeatures.map((f) => `  - ${f}`).join("\n")}

## 10. Phased Development Roadmap
${roadmapMd}

## 11. Risks, Challenges & Mitigations
${risksMd}

## 12. Possible Improvements (v1.1+)
${blueprint.possibleImprovements.map((imp) => `- ${imp}`).join("\n")}

## 13. Future Academic Scope & Research Angles
${blueprint.futureScope.map((scope) => `- ${scope}`).join("\n")}

---
*Generated by CapstoneAI — Project Feasibility & Innovation Engine for University Students.*
`;
}
